---
# install/upgrade OMERO.server

- name: omero server | is server symlink present
  become: yes
  stat:
    path: "{{ omero_server_basedir }}/{{ omero_server_symlink }}"
  register: omero_server_symlink_st

# This should be safe to always run including in check-mode
- name: omero server | get server version
  become: yes
  become_user: "{{ omero_server_system_user }}"
  command: "{{ omero_server_basedir }}/{{ omero_server_symlink }}/bin/omero version"
  register: omero_server_version
  when: omero_server_symlink_st.stat.exists
  changed_when: False
  check_mode: no
  # Set a custom error message
  ignore_errors: yes

- name: omero server | check omero version could be obtained
  assert:
    msg: "OMERO.server found but unable to get version, you may have a corrupt installation"
    that: "not (omero_server_symlink_st.stat.exists and omero_server_version is undefined)"

# TODO: If server was started by systemd but stopped directly you may end up
# with a hanging process

# Check whether an upgrade is available since `omego upgrade` always
# restarts the server
- name: omero server | get latest downloads url
  uri:
    url: https://downloads.openmicroscopy.org/latest/omero
    method: HEAD
  register: _omero_server_downloads_latest
  check_mode: no

# omego supports --release "latest" but not "present"
# It's easiest to lookup a concrete version and use this for all omego
# operations instead
- name: omero server | get latest version
  set_fact:
    _omero_server_new_version: "{{
      (omero_server_release in ('latest', 'present')) | ternary(
         _omero_server_downloads_latest.url.strip('/').split('/')[-1],
         omero_server_release
      )
  }}"

- name: omero server | checkupgrade
  set_fact:
    # Experimentation shows "5.3.2 | version_compare('latest', '<')" is False
    # so this should work as expected
    _omero_server_update_needed: "{{
      omero_server_symlink_st.stat.exists and
      (omero_server_version.stdout | version_compare(
         _omero_server_new_version,
         omero_server_checkupgrade_comparator))
    }}"

- debug:
    msg: "Upgrade needed: {{ omero_server_version.stdout }} -> {{ omero_server_release }}"
  when: _omero_server_update_needed

- name: omero server | set upgrade flag
  set_fact:
    _omero_server_execute_upgrade: "{{
      omero_server_upgrade and
      _omero_server_update_needed and
      (omero_server_release != 'present')
    }}"

- name: omero server | install omero
  become: yes
  become_user: "{{ omero_server_system_user }}"
  command: >
    {{ omero_server_omego }}
    install
    {{ omero_server_omego_options }}
    {{ omero_server_omego_db_options }}
    --rootpass {{ omero_server_rootpassword | quote }}
  args:
    chdir: "{{ omero_server_basedir }}"
    creates: "{{ omero_server_basedir }}/{{ omero_server_symlink }}"
  notify:
    - omero-server rewrite omero-server configuration
    - omero-server restart omero-server

# Backup database

- name: omero server | create omero backup directory
  become: yes
  file:
    mode: 0700
    owner: "{{ omero_server_system_user }}"
    path: "{{ omero_server_database_backupdir }}"
    state: directory
  when: (omero_server_database_backupdir | length > 0) and _omero_server_execute_upgrade

- name: omero server | backup database
  become: yes
  become_user: "{{ omero_server_system_user }}"
  command: >
    {{ omero_server_omego }}
    db dump
    {{ omero_server_omego_db_options }}
    --serverdir {{ omero_server_basedir }}/{{ omero_server_symlink }}
  args:
    chdir: "{{ omero_server_database_backupdir }}"
  when: (omero_server_database_backupdir | length > 0) and _omero_server_execute_upgrade

# Upgrade
- name: omero server | upgrade
  become: yes
  become_user: "{{ omero_server_system_user }}"
  command: >
    {{ omero_server_omego }}
    install --upgrade
    {{ omero_server_omego_options }}
    {{ omero_server_omego_db_options }}
  args:
    chdir: "{{ omero_server_basedir }}"
  when: _omero_server_execute_upgrade
  notify:
    - omero-server rewrite omero-server configuration
    - omero-server restart omero-server
